asp.net_mvc-webapp/Models/Exam1.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace asp.net_mvc_webapp.Models
{
    public class Exam1
    {
        public string Name { get; set; }
    }
}

asp.net_mvc-webapp/Controllers/Exam1Controller.cs
using asp.net_mvc_webapp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace asp.net_mvc_webapp.Controllers
{
    public class Exam1Controller : Controller
    {
        // GET: Customers
        public ActionResult Index()
        {
            var model = new List<Exam1>();
            
            model.Add(new Exam1 { Name = "John Smith" });
            model.Add(new Exam1 { Name = "Mary Williams" });
            
            return View(model);
        }

        public ActionResult Details(int id)
        {
            //passing data controller to view
            ViewBag.Message = id;
            return View();
        }        
    }
}

asp.net_mvc-webapp/Views/Exam1/Details.cshtml
@model IEnumerable<asp.net_mvc_webapp.Models.Exam1>

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@* passing data controller to view *@

@{int i = 1;}
@foreach (var item in Model)
{
    //if (ViewBag.Message == i)
    //{
        <h2>@item.Name</h2>
        //}
        i++;
    }

asp.net_mvc-webapp/Views/Exam1/Index.cshtml
@*@model asp.net_mvc_webapp.Model*@
@model IEnumerable<asp.net_mvc_webapp.Models.Exam1>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Customer</h2>

<table class="table table-bordered table-hover">
    <tr>
        <td>
            <b>Customer</b>
        </td>
    </tr>
    @{int i = 1;}
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.ActionLink(@item.Name, "Details", "Exam1", new { id = @i }, null)</td>
            @{i++;}
        </tr>
    }
    <tr>
        <td>
            enable-migrations
            add-migration InintialModel
            add-migration InintialModel -force
            update-database
            add-migration AddIsSubscribedToCustomer
            Update-Database
        </td>
    </tr>
</table>